name: sandwich-club
repository:
    type: git
    url: https://github.com/GuyOhm/sandwich-club
    stats:
        watches: 0
        stars: 0
        forks: 0
url: https://github.com/GuyOhm/sandwich-club
