name: Praline-cashmere
repository:
    type: git
    url: https://github.com/ManyCore-NLeSC/Praline-cashmere
    stats:
        watches: 1
        stars: 0
        forks: 0
url: https://github.com/ManyCore-NLeSC/Praline-cashmere
