name: cocos2d
repository:
    type: git
    url: https://github.com/ZhouWeikuan/cocos2d
    stats:
        watches: 91
        stars: 600
        forks: 295
url: https://code.google.com/archive/p/cocos2d-android-1/
