name: xslt-library
repository:
    type: git
    url: https://github.com/Offer-Ready/xslt-library
    stats:
        watches: 2
        stars: 0
        forks: 0
url: https://github.com/Offer-Ready/xslt-library
