name: igi2-multiplayer-launcher-masterserver
repository:
    type: git
    url: https://github.com/hyperxpro/igi2-multiplayer-launcher-masterserver
url: https://github.com/hyperxpro/igi2-multiplayer-launcher-masterserver
