name: Rajawali
repository:
    type: git
    url: https://github.com/Rajawali/Rajawali
    stats:
        watches: 202
        stars: 1748
        forks: 627
url: https://plus.google.com/u/0/communities/116529974266844528013
