name: poei-2018-cgi-base-spring
repository:
    type: git
    url: https://github.com/jponcy/poei-2018-cgi-base-spring
    stats:
        watches: 1
        stars: 0
        forks: 0
url: https://github.com/jponcy/poei-2018-cgi-base-spring
